name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main

env:
  REGION: northamerica-northeast2
  GCP_PROJECT_ID: test-project-1

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Google Cloud authentication
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.ARTIFACT_REGISTRY_WRITER }}

    # Step 3: Configure Docker for Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev

    # Step 4: Build the Docker image
    - name: Build Docker Image
      run: |
        IMAGE_NAME=$REGION-docker.pkg.dev/$GCP_PROJECT_ID/bash:latest
        docker build -t $IMAGE_NAME .

    # Step 5: Push the Docker image to Artifact Registry
    - name: Push Docker Image
      run: |
        IMAGE_NAME=$REGION-docker.pkg.dev/$GCP_PROJECT_ID/bash:latest
        docker push $IMAGE_NAME
